name: im_legends
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  flutter_native_splash: ^2.4.6
  # State management BoC
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  # Firebase
  firebase_core: ^4.0.0
  # Supabase
  supabase_flutter: ^2.9.1
  meta: ^1.16.0
  image_picker: ^1.2.0
  go_router: ^16.2.1
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ImLogo.png"
  adaptive_icon_foreground: "assets/images/ImLogo.png"
  remove_alpha_ios: true

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    # - .env
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf

    - family: Borel
      fonts:
        - asset: assets/fonts/Borel/Borel-Regular.ttf

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-VariableFont_wght.ttf
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-MediumItalic.ttf
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
